flowchart LR
    A["0x00000000<br>new-firmware<br>User Image"] -->
    B["0x00030000<br>old-firmware<br>Persistent Fallback"] -->
    C["0x00052000<br>Metadata"] -->
    D["0x00054000<br>Recovery"] -->
    E["0x00056000<br>BIM + CCFG<br>Kritik Alan"]
